config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  mount ActionCable.server => '/websocket'
  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    member do
      patch :move
    end
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'angular', to: 'portfolios#angular'
  
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news' 

  resources :blogs do
    member do
      get 'toggle_status'
    end
  end

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  acts_as_list
  has_many :technologies, dependent: :destroy
  accepts_nested_attributes_for :technologies,
                                 reject_if: proc { |attributes| attributes['name'].blank? },
                                 allow_destroy: true
  validates :title, :body, presence: true

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.angular
    where(subtitle: "Angular")
  end

  def self.by_position
    order("position ASC")
  end

  scope :ruby_on_rails_portfolio_items, -> {where(subtitle: "Ruby on Rails")}
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy, :move]
  layout "portfolio"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all
  def index
    @portfolio_items = Portfolio.by_position
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def move
    @portfolio_item.insert_at(params[:position].to_i)
    head :ok
  end
  def new
    @portfolio_item = Portfolio.new
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
        if @portfolio_item.save
          format.html { redirect_to portfolios_path, notice: 'Your portfolio item is now live.' }
        else
          format.html { render :new }
        end
    end
  end

  def edit 
  end

  def show
  end
  
  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: 'Record was successfully removed.' }
    end
  end

  def update
    respond_to do |format|
        if @portfolio_item.update(portfolio_params)
          format.html { redirect_to portfolios_path, notice: 'portfolio was successfully updated.' }
        else
          format.html { render :edit } 
        end
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title, 
                                      :subtitle, 
                                      :body,
                                      :main_image,
                                      :thumb_image,
                                      technologies_attributes: [:name, :id, :_destroy]
                                     )
  end

  def set_portfolio
    @portfolio_item = Portfolio.find(params[:id])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height, width)
    "https://via.placeholder.com/#{height}x#{width}"
  end

  def portfolio_img img, type
    if img && img != ''
      img
    elsif type == "thumb"
      image_generator 350, 200
    else
      image_generator 600, 400
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_for portfolio_item do |f| %>
  <div class="row">
    <div class="col-md-6">
      <% if portfolio_item.errors.any? %>
        <div id="notice_wrapper">
          <% portfolio_item.errors.full_messages.each do |message| %>
            <p><%= message %></p>
          <% end %>
        </div> 
      <% end %>
      <div class = "form-group">
        <%= f.label :title, 'Title'%>:
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class = "form-group">
        <%= f.label :subtitle, 'Subtitle' %>:
        <%= f.text_field :subtitle, class: "form-control" %>
      </div>
      <div class = "form-group">
        <label class="btn btn-primary">
          Upload a thumb image file <%= f.file_field :thumb_image, style: "display:none;" %>
        </label>
      </div>
      <div class = "form-group">
        <label class="btn btn-primary">
          Upload a main image file <%= f.file_field :main_image, style: "display:none;" %>
        </label>
      </div>

    </div>

    <div class="col-md-6">
      <div class = "form-group">
        <%= f.label :body, 'Body' %>:
        <%= f.text_area :body, class: "form-control", rows: "15" %><br>
      </div>
    </div>
    
    <div class="col-md-12">
      <h2>Technologies Used:</h2>
      <div id=technologies>
        <%= f.fields_for :technologies do |technology_form| %>
          <%= render 'technology_fields', f: technology_form %> 
        <% end %>
        <div class='links'>
          <%= link_to_add_association 'add technology', f, :technologies %>
        </div>
      </div>

      <div class="form-group">
        <%= f.submit "Save Portfolio Item", class: "btn btn-primary btn-block" %>
      </div>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div data-id="<%= portfolio_item.id %>" class="portfolio-card-wrapper m-2 ml-4">
  <div class="card mb-2 mr-3 shadow-sm">
    <%= image_tag (portfolio_img portfolio_item.thumb_image.to_s, 'thumb'), class: "bd-placeholder-img card-img-top img-fluid" %>
    <div class="card-body">
      <p class="card-text">
        <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %>
        <%= portfolio_item.subtitle %>
        <%= link_to "Delete Portfolio",  portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin)%>
      </p>
    </div> 
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class='nested-fields'>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <%= link_to_remove_association "remove technology", f %>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>
<%= link_to "Create New Portfolio", new_portfolio_path %>
<% @angular_portfolio_items.each do |angular_portfolio| %>
    <p><%= angular_portfolio.title %></p>
    <h2><%= link_to angular_portfolio.subtitle, portfolio_show_path(angular_portfolio) %></h2>
    <p><%= angular_portfolio.body %></p>
    <%= image_tag angular_portfolio.thumb_image if !angular_portfolio.thumb_image.nil? %>
    <%= link_to "Edit", edit_portfolio_path(angular_portfolio) %>
    <%= link_to 'Delete Portfolio Item', angular_portfolio, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %> 

app/views/portfolios/edit.html.erb
<div class="container mt-4">
  <h1>Edit This Portfolio Item</h1>
  <%= render "form", portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <%= source_helper("alert alert-warning") %>
    <% if logged_in?(:site_admin) %>
      <p><%= link_to 'Create New Portfolio', new_portfolio_path %></p>
    <% end %>
    <div class="row justify-content-center" id="items" data-controller="<%= 'drag' if logged_in?(:site_admin) %>">
      <%= render partial: "portfolio_item", collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container mt-4">
  <h1>Create a new Portfolio Item</h1>
  <%= render "form", portfolio_item: @portfolio_item %> 
</div>

app/views/portfolios/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7 mt-4">
      <%= image_tag (portfolio_img @portfolio_item.main_image.to_s, 'main'), width: "100%" %>
    </div>

    <div class="col-md-5 mt-4">
      <h1><%= @portfolio_item.title %></h1>
      <hr>
      <em><%= @portfolio_item.subtitle %></em>
      <div id="body-wrap"><p><%= @portfolio_item.body %></p></div>
      <hr>
      <h3>Technologies Used:</h3>
      <% @portfolio_item.technologies.each do |technology| %>
        <p><%= technology.name %></p>
      <% end %>

      <% if logged_in?(:site_admin) %>
        <%= link_to "Edit Item", edit_portfolio_path(@portfolio_item), class:"btn btn-warning" %>
      <% end %>
    </div>
  </div>
</div>