config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  mount ActionCable.server => '/websocket'
  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    member do
      patch :move
    end
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'angular', to: 'portfolios#angular'
  
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news' 

  resources :blogs do
    member do
      get 'toggle_status'
    end
  end

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p class="app-footer"><%= @copyright %></p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Samuel Atobatele</h3>
    <nav class="nav-masthead app-nav navbar navbar-expand-lg navbar-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= nav_helper "span", "navigation" %>
          <%= login_helper "navigation" %>
        </div>
      </div>
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p><%= @copyright %></p>
</footer>

app/views/shared/_blog_main.html.erb
<h1 class="pb-3 mb-3">My Blogs</h1>
<%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
<%= link_to 'Topics', topics_path %>
<hr>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-light d-flex navbar-expand-lg blog-nav">
  <%= link_to "Samuel Atobatele", root_path, class: "blog-links mr-5" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse ml-5" id="navbarNavAltMarkup">
    <div class="navbar-nav ml-5 pl-5">
      <%= nav_helper "span", "blog-links" %>
      <span><%= login_helper "p-4 blog-links" %></span>
    </div>
  </div>
</nav>

app/views/shared/_blog_pagination.html.erb
<nav class="blog-pagination">
  <a class="btn btn-outline-primary" href="#">Older</a>
  <a class="btn btn-outline-secondary disabled" href="#" tabindex="-1" aria-disabled="true">Newer</a>
</nav>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-4 mb-3 bg-light rounded">
    <h4>About Me</h4>
    <p class="mb-0"><em>Learning has always been my passion</em></p>
  </div>

  <%= source_helper("alert alert-info p-4 mb-3 bg-light rounded") %>

  <div class="p-4 mb-3 bg-light rounded">
    <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>

  <div class="p-4">
    <h4>Follow Me</h4>
    <ol class="list-unstyled social-links">
    <li><a href="https://github.com/CodedSam84"><%= fa_icon "github" %></a></li>
    <li><a href="https://www.instagram.com/samatob/"><%= fa_icon "instagram" %></a></li>
    <li><a href="https://www.linkedin.com/in/samuel-atobatele-673858ab/"><%= fa_icon "linkedin" %></a></li>
    <li><a href="https://twitter.com/swumatob"><%= fa_icon "twitter" %></a></li>
    </ol>
  </div>
</aside>

app/views/shared/_flash_messages.html.erb
<% if notice %>
  <div id="notice_wrapper">
    <p class="notice"><%= notice %></p>
  </div> 
<% elsif alert %>
  <div id="notice_wrapper">
    <p class="alert"><%= alert %></p>
  </div>
<% end %> 

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "View all Portfolio Items", portfolios_path %>/
      <a href="#">Back to top</a>
    </p>
    <p><%= @copyright %></p>
  </div>
</footer> 

app/views/shared/_portfolio_header.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>My Portfolio</h1>
    <p class="lead text-muted">In this portfolio you will find all the web applications I have worked on so far.</p>
    <p>
    <%= link_to "About Me", about_me_path, class: "btn btn-primary my-2" %>
    <%= link_to "My Blogs", blogs_path, class: "btn btn-secondary my-2" %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">After several years working as an engineer in the manufaturing industry, 
              I decided it was time to pursue a long-held goal of becoming a developer.
              Here you will find some of the projects I have done in my exciting journey in the world of tech!</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Explore</h4>
              <ul class="list-unstyled">
                <%= nav_helper "li", "text-white" %>
                <li><%= login_helper "text-white" %></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
          <%= link_to "Samuel Atobatele", root_path, class: "navbar-brand d-flex align-items-center" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>